#!/bin/bash

# tweet while u hack


oauth_token="17993005-8aPbawsYZF1kprEsDXFVIUy3ghCSPudC3SEu8YdwE"
oauth_token_secret="Letj5xDTNFqlpvQQbY6LIFQdKPFs3LdQlkZCkfzT9U"

oauth_nonce=""
refresh_nonce() {
	oauth_nonce="md5sum <<< \"$RANDOM-$(date +%s.%N)\" | cut -d' ' -f 1"
}

pe() { 
	echo -n "$@" | perl -p -e 's/([^A-Za-z0-9-._~])/sprintf("%%%02X", ord($1))/seg'
}

oauth_consumer_key="f0SI6q2G4qFnEDS1o5kjGw"
oauth_signature=""
oauth_signature_method="HMAC-SHA1"
oauth_timestamp="$(date +%s)"
oauth_version="1.0"

# here it is. oauth can bite me. what a dumb implementation.
# dont ruin it for my users. twitter will give you one for free.
oauth_consumer_secret="PkWaVAkqzlbE2bbIfkl8Zbmyh6alvwekF77snqgZI"

tstatus="i just want to say sorry to all my fans for removing my post about my project. i got discouraged. #watdo http://www.youtube.com/watch?v=AXwGVXD7qEQ"
#base_url="https://api.twitter.com/1.1/statuses/update.json"


basestring="POST&$(pe $base_url)&$(pe $perameterstring)"

signingkey="$(pe $oauth_consumer_secret)&$(pe $oauth_token_secret)"

oauth_signature="$(echo -n "$basestring" | openssl dgst -sha1 -binary -hmac "$signingkey" | base64)"

auth_header="Authorization: OAuth oauth_consumer_key=\"$oauth_consumer_key\", oauth_nonce=\"$oauth_nonce\", oauth_signature=\"$(pe $oauth_signature)\", oauth_signature_method=\"$oauth_signature_method\", oauth_timestamp=\"$oauth_timestamp\", oauth_token=\"$oauth_token\", oauth_version=\"$oauth_version\""

verbose_output() {
	echo "oauth_consumer_key     : $oauth_consumer_key"
	echo "oauth_nonce            : $oauth_nonce"
	echo "oauth_signature        : $oauth_signature"
	echo "oauth_signature_method : $oauth_signature_method"
	echo "oauth_timestamp        : $oauth_timestamp"
	echo "oauth_token            : $oauth_token"
	echo "oauth_version          : $oauth_version"
	echo "---"
	echo "oauth_token_secret     : $oauth_token_secret"
	echo "consumer_secret        : $oauth_consumer_secret"
	echo "status                 : $tstatus"
	echo "base_url               : $base_url"
	echo "perameterstring : $perameterstring"
	echo "basestring : $basestring"
	echo "signingkey      : $signingkey"
	echo "oauth_signature : $oauth_signature"
	echo "auth_header     : $auth_header"
}

status_update() {

	refresh_nonce
	base_url="https://api.twitter.com/1.1/statuses/update.json"
	perameterstring="oauth_consumer_key=$oauth_consumer_key&oauth_nonce=$oauth_nonce&oauth_signature_method=$oauth_signature_method&oauth_timestamp=$oauth_timestamp&oauth_token=$oauth_token&oauth_version=$oauth_version&status=$(pe $tstatus)"



	curl -v -H "$auth_header" --data-urlencode "status=$tstatus" "$base_url"

}
